### ISSUE TITLE
[feature]: Add more samples integrated with Keploy #26 

### ISSUE THREAD

**Issue by mrjayrai** [keploy/samples-java#33] opened 2023-02-26 18:42 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Hello,

I noticed that you have posted an issue on GitHub regarding a problem you are facing with one of the features. I would like to offer my assistance in helping you resolve this issue.

Please let me know how I can help and what steps you have already taken to troubleshoot the issue. I will do my best to provide any guidance or support needed to find a solution.

Thank you for considering my offer to help.

Best regards,
Pritesh Rai

### Why should this be worked on?

**Keploy** is a deployment tool that helps automate the process of deploying software applications to servers or cloud environments. By integrating the samples with keploy, it means that the code examples will be configured to work with keploy and can be easily deployed using this tool.

Including more samples integrated with keploy would make it easier for developers or users to understand how keploy works and how it can be used to deploy their own applications. It would also provide them with practical examples to help them get started using the tool.

**Comment by Sarthak160** [comment] 2023-02-27 06:19
yes you can work on this if you want @mrjayrai

**Comment by gouravkrosx** [comment] 2023-03-02 07:27
Duplicate of https://github.com/keploy/samples-java/issues/26, hence closing.

**Closed by gouravkrosx** 2023-03-02 07:27 UTC
